==== DescribeEOCoverageSet Response PhenomenonTime
[cols=">20h,<80d",width="100%"]
|===
|Test id: |/conf/eowcs/describeEOCoverageSet-response-phenomenonTime
|Test purpose: |<</req/eowcs/describeEOCoverageSet-response-phenomenonTime>>
|Test method:
a|
Send otherwise valid _DescribeEOCoverageSet_ requests containing a
`wcs:CoverageDescription` section and a time interval to server under test.
Check that:

* if the request parameter `containment` is of value `overlaps` or is omitted,
  the response contains only descriptions of EO Coverages whose time interval
  defined by its
  `eop:EarthObservation/om:phenomenonTime/gml:TimePeriod/gml:beginPosition` and `eop:EarthObservation/om:phenomenonTime/gml:TimePeriod/gml:endPosition`
  elements in `wcseo:EOMetadata` overlaps with the request time extent;
* if request parameter `containment` is of value `contains`, the response
  contains only descriptions of EO Coverages whose time interval defined by its
  `eop:EarthObservation/om:phenomenonTime/gml:TimePeriod/gml:beginPosition` and
  `eop:EarthObservation/om:phenomenonTime/gml:TimePeriod/gml:endPosition`
  elements in `wcseo:EOMetadata` is completely contained within the request time
  extent;

Pass test if both checks succeed.
|===
