==== Temporal Validity Stitched Mosaic
[cols=">20h,<80d",width="100%"]
|===
|Test id: |/conf/eowcs/temporal-validity-stitched-mosaic
|Test purpose: |<</req/eowcs/temporal-validity-stitched-mosaic>>
|Test method:
a|
For each Stitched Mosaic offered by the server under test:

* retrieve the time interval _t_ of the Stitched Mosaic given by its
  `eop:EarthObservation/om:phenomenonTime/gml:TimePeriod/gml:beginPosition` and
  `eop:EarthObservation/om:phenomenonTime/gml:TimePeriod/gml:endPosition`
  elements in `wcseo:EOMetadata` via _DescribeCoverage_,
  _DescribeEOCoverageSet_, and _GetCoverage_ operations.
* Check that all responses contain the same time interval information. +
For each obtained dataset _d_:
** retrieve the time interval _t~i~_ of `dataset` _d_ given by its
   `eop:EarthObservation/om:phenomenonTime/gml:TimePeriod/gml:beginPosition` and
   `eop:EarthObservation/om:phenomenonTime/gml:TimePeriod/gml:endPosition`
   elements in `wcseo:EOMetadata` via _DescribeCoverage_,
   _DescribeEOCoverageSet_, and _GetCoverage_ operations.
** Check that all responses contain the same time interval information.
* Check that _t_ is the minimal time interval containing the temporal validities
  of all Datasets the Stitched Mosaic refers to.

Test passes if all individual tests pass.
|===
