[preface]
== Foreword

This WCS Application Profile for Earth Observation is an OGC Interface Standard
which relies on WCS 2.0 (the Core [OGC 09-110r4] plus selected extensions), the
Coverages Implementation Schema (renamed from GML Application Schema -
Coverages) [OGC 09-146r2], the Earth Observation Metadata Profile of
Observations and Measurements [OGC 10-157r4], and GML 3.2.1 [OGC 07-036].

This document includes three annexes; the first two annexes are normative.

_Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. The Open Geospatial Consortium
shall not be held responsible for identifying any or all such patent rights._

_Recipients of this document are requested to submit, with their comments,
notification of any relevant patent claims or other intellectual property rights
of which they may be aware that might be infringed by any implementation of the
standard set forth in this document, and to provide supporting documentation._

== Introduction

The OGC _Web Coverage Service (WCS) Application Profile - Earth Observation_
(EO- WCS), defines a profile of WCS 2.0 [OGC 09-110r4] for use on Earth
Observation data. An Application Profile bundles several specifications and
possibly adds additional requirements on an implementation. Extra requirements
can be additions (for example, Dataset Series are introduced by this
specification) or constraints (for example, coverages offered are restricted to
2-D rasters).

EO-WCS provides the following specification elements:

* Definition of specific Earth Observation coverages (EO Coverages) which have a
latitude/longitude or projected x/y spatial extent and a temporal validity
extent. EO Coverages are derived from Referenceable Grid Coverages and Rectified
Grid Coverages as defined in the Coverage Implementation Schema (renamed from
GML Application Schema - Coverages) [OGC 09-146r2]. Each EO Coverage has an
EO metadata set [OGC 10-157r4] contained in its metadata which describes the
coverage on hand on a higher semantic level.

* Definition of a hierarchy which allows to group EO Coverages suitably for an
efficient retrieval:

** Datasets as plain 2-D EO Coverages (and, hence, accessible as coverages);

** Stitched Mosaics as homogeneous collections of spatially non-overlapping
subsets of Datasets, accessible themselves as coverages;

** Dataset Series as collections of Stitched Mosaics, Datasets, and/or Dataset
Series; Dataset Series themselves are not coverages.

* Bundling of several mandatory and optional WCS extensions for EO-WCS
implementations.
