= OGC® Web Coverage Service 2.0 Interface Standard - Earth Observation Application Profile

== Scope

This OGC WCS Application Profile - Earth Observation Interface Standard -
henceforth abbreviated as: _WCS Earth Observation Application Profile (EO-WCS)_
- defines data structures and operations which together allow retrieval of Earth
Observation coverages offered by a WCS 2.0 server.

== Conformance

This document establishes the following requirements and conformance classes:

* _eowcs_, of URI
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.1/req/eowcs,
defining EO-WCS on conceptual level in Clauses <<eo_data_model>>,
<<eo_service_model>>, and <<wcs_extensions>>; the corresponding conformance
class is _eowcs_, with URI
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.1/conf/eowcs.

* _eowcs_geteocoverageset_, of URI
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.1/req/eowcs_geteocoverageset,
defining the GetEOCoverageSet request of EO-WCS in Clause <<eo_service_model>>
where stated, particularly subclause <<geteocoverageset_operation>>; the
corresponding conformance class is _eowcs_geteocoverageset_, with URI
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.1/conf/eowcs_geteocoverageset.

* _eowcs_get-kvp_, of URI
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.1/req/eowcs_get-kvp,
defining the GET-KVP protocol binding of EO-WCS in Subclause 9.2; the
corresponding conformance class is _eowcs_get-kvp_, with URI
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.1/conf/eowcs_get-kvp.

* _eowcs_soap_, of URI
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.1/req/eowcs_soap,
defining the SOAP protocol binding of EO-WCS on conceptual level in Subclause
9.3; the corresponding conformance class is _eowcs_soap_, with URI
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.1/conf/eowcs_soap.

Standardization target of all requirements and conformance classes are EO-WCS
implementations (currently: servers).

Requirements and conformance test URIs defined in this document are relative to
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.1/.

<<__normative_abstract_test_suite>> lists the conformance tests which shall be
exercised on any software artifact claiming to implement EO-WCS.

[#normative_references,reftext='3']
== Normative references

This _OGC WCS Application Profile - Earth Observation_ specification consists of
the present document and an
http://schemas.opengis.net/wcs/wcseo/1.1/[XML Schema]. The complete
specification is identified by OGC URI
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.1,
the document has OGC URI
http://www.opengis.net/doc/IS/WCS_application-profile_earth-observation/1.1.

The complete specification is available for download from
http://www.opengeospatial.org/standards/wcs; additionally, the XML Schema is
posted online at http://schemas.opengis.net/wcs/wcseo/1.1 as part of the OGC
schema repository. In the event of a discrepancy between bundled and schema
repository versions of the XML Schema files, the schema repository shall be
considered authoritative.

The following normative documents contain provisions that, through reference in
this text, constitute provisions of this specification. For dated references,
subsequent amendments to, or revisions of, any of these publications do not
apply. For undated references, the latest edition of the normative document
referred to applies.

OGC 06-121r9, _OGC Web Services Common Standard_, version 2.0

OGC 09-146r2, _OGC® Coverage Implementation Schema_ (renamed from _OGC®
GML Application Schema - Coverages_), version 1.0 +
Conformance classes used: _gml-coverage_, _gml_, _multipart_, _special-format_

OGC 09-110r4, _OGC® WCS 2.0 Interface Standard- Core: Corrigendum_, version
2.0 +
Conformance classes used: _core_

OGC 11-053r1, _OGC® Web Coverage Service Interface Standard - CRS Extension_,
version 1.0 +
Conformance classes used: _crs_, _crs-gridded-coverage_

OGC 12-039, _OGC® Web Coverage Service Interface Standard - Scaling Extension_,
version 1.0 +
Conformance classes used: _scaling_

OGC 12-040, _OGC® Web Coverage Service Interface Standard - Range Subsetting
Extension_, version 1.0 +
Conformance classes used: _record-subsetting_

OGC 12-049, _OGC® Web Coverage Service Interface Standard - Interpolation
Extension_, version 1.0 +
Conformance classes used: _interpolation_

OGC 09-147r3, _OGC® Web Coverage Service 2.0 Interface Standard - KVP Protocol
Binding Extension - Corrigendum_, version 1.0 +
Conformance classes used: _get-kvp_

OGC 09-149r1, _OGC® Web Coverage Service 2.0 Interface Standard - XML/SOAP
Protocol Binding Extension_, version 1.0 +
Conformance classes used: _soap_

OGC 12-100r1, _OGC® GML Application Schema - Coverages - GeoTIFF Coverage
Encoding Profile_, version 1.0 +
Conformance classes used: _geotiff-coverage_

OGC 14-100r2, _OGC® CF-netCDF 3.0 encoding using GML Coverage Application
Schema_, version 2.0 +
Conformance classes used: _CF-netCDF-1.6 GML encoding_, _CF-netCDF-1.6 data
format_, _CF-netCDF-1.6 multipart data encoding_

OGC 12-108, _OGC® GML Application Schema - Coverages JPEG2000 Coverage Encoding
Extension_, version 1.0 +
Conformance classes used: _jpeg2000-coverage_

OGC 10-157r4, _OGC® Earth Observation Metadata profile of Observations &
Measurements_, version 1.1 +
Conformance classes used: _eop_, _sar_, _opt_

== Terms and definitions

For the purposes of this document, the terms and definitions given in the above
references apply. In addition, the following terms and definitions apply. An
arrow "->" indicates that the following term is defined in this Clause.

=== Coverage

digital representation of a spatio-temporally varying phenomenon as defined in
[OGC 09-146r2]

=== Dataset

2-D -> EO Coverage

NOTE: A Dataset usually represents observations obtained by satellite
instruments.

=== Dataset Series

collection of -> EO Coverages

=== EO Coverage

Rectified Grid -> Coverage or Referenceable Grid -> Coverage having an -> EO
Metadata record and a WGS84 bounding box

=== EO Metadata

-> EO Coverage's metadata record

=== Stitched Mosaic

-> EO Coverage composed from subsets of one or more co-referenced -> Datasets

=== EO Product

An EO Product contains one or more related -> EO Product Datasets plus metadata
and optionally auxiliary data like -> EO Product Quicklooks.

=== EO Product Dataset

One or more files each containing one or more -> EO Coverages.

=== EO Product Quicklook

A visual representation of a usually reduced -> EO Product Dataset encoded in
an image format. The -> EO Product Dataset may combine different bands.

=== Lineage record

Data structure documenting an operation that has been applied to the -> coverage
it is part of

=== refers to

contains, in its -> EO Metadata element as defined in [OGC 10-157r4], the -> EO
Metadata element of

== Conventions

=== UML notation

Unified Modeling Language (UML) static structure diagrams appearing in this
specification are used as described in Subclause 5.2 of OGC Web Services Common
[OGC 06-121r9].

=== Data dictionary tables

The UML model data dictionary is specified herein in a series of tables. The
contents of the columns in these tables are described in Subclause 5.5 of [OGC
06-121r9]. The contents of these data dictionary tables are normative, including
any table footnotes.

=== Namespace prefix conventions

The following namespaces are used in this document. The prefix abbreviations
used constitute conventions used here, but are *not* normative. The namespaces
to which the prefixes refer are normative, however.

[#namespace_mappings,reftext='{table-caption} {counter:table-num}']
.Namespace mappings
[cols="^1,2*4",options="header"]
|===============================================================================
|Prefix |Namespace URI                          |Description
|xsd    |http://www.w3.org/2001/XMLSchema       |XML Schema namespace
|ows    |http://www.opengis.net/ows/2.0         |OWS Common 2.0
|gml    |http://www.opengis.net/gml/3.2         |GML 3.2.1
|gmlcov |http://www.opengis.net/gmlcov/1.0      |Coverages Implementation Schema
1.0
|wcs    |http://www.opengis.net/wcs/2.0         |WCS 2.0
|eop    |http://www.opengis.net/eop/2.1         |Earth Observation Metadata
Profile of Observations and Measurements
|opt    |http://www.opengis.net/opt/2.1         |Optical Earth Observation
Metadata Profile of Observations and Measurements (extension of eop)
|sar    |http://www.opengis.net/sar/2.1         |SAR Earth Observation Metadata
Profile of Observations and Measurements (extension of eop)
|wcseo  |http://www.opengis.net/wcs/wcseo/1.1   |WCS Application Profile - Earth
Observation 1.1
|scal   |http://www.opengis.net/wcs/scaling/1.0 (schema uses
http://www.opengis.net/WCS_service-extension_scaling/1.0) |WCS Scaling Extension
|int    |http://www.opengis.net/wcs/interpolation/1.0 (schema uses
http://www.opengis.net/WCS_service-extension_interpolation/1.0|WCS Interpolation
Extension
|crs    |http://www.opengis.net/wcs/crs/1.0     |WCS CRS Extension
|gmd    |http://www.isotc211.org/2005/gmd       |ISO 19139 Metadata
|gmi    |http://standards.iso.org/iso/19115/-2/gmi/1.0 or
http://www.isotc211.org/2005/gmi |ISO 19139-2 Metadata
|mdb    |http://standards.iso.org/iso/19115/-3/mdb/1.0 |ISO 19115-3 Metadata
|===============================================================================

=== Multiple representations

When multiple representations of the same information are given in a
specification document these are consistent. Should this not be the case then
this is considered an error, and the
http://schemas.opengis.net/wcs/wcseo/1.1/[XML Schema] shall take precedence.
