= OGC® Web Coverage Service 2.0 Interface Standard - Earth Observation Application Profile

== Scope

This OGC WCS Application Profile - Earth Observation Interface Standard -
henceforth abbreviated as: _WCS Earth Observation Application Profile (EO-WCS)_
- defines data structures and operations which together allow retrieval of Earth
Observation coverages offered by a WCS 2.0 server.

== Conformance

This document establishes the following requirements and conformance classes:

* _eowcs_, of URI
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.0/req/eowcs,
defining EO-WCS on conceptual level in Clauses <<eo_data_model>>,
<<eo_service_model>>, and <<wcs_extensions>>; the corresponding conformance
class is _eowcs_, with URI
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.0/conf/eowcs.

* _eowcs_get-kvp_, of URI
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.0/req/eowcs_get-kvp,
defining the GET-KVP protocol binding of EO-WCS in Subclause 9.2; the
corresponding conformance class is _eowcs_get-kvp_, with URI
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.0/conf/eowcs_get-kvp.

* _eowcs_soap_, of URI
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.0/req/eowcs_soap,
defining the SOAP protocol binding of EO-WCS on conceptual level in Subclause
9.3; the corresponding conformance class is _eowcs_soap_, with URI
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.0/conf/eowcs_soap.

Standardisation target of all requirements and conformance classes are EO-WCS
implementations (currently: servers).

Requirements and conformance test URIs defined in this document are relative to
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.0/.

Annex A lists the conformance tests which shall be exercised on any software
artefact claiming to implement EO-WCS.

== Normative references

This _OGC WCS Application Profile - Earth Observation_ specification consists of
the present document and an XML Schema. The complete specification is identified
by OGC URI
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.0,
the document has OGC URI
http://www.opengis.net/doc/ISx/WCS_application-profile_earth-observation/1.0.

The complete specification is available for download from
http://www.opengeospatial.org/standards/wcs; additionally, the XML Schema is
posted online at http://schemas.opengis.net/wcs/wcseo/1.0 as part of the OGC
schema repository. In the event of a discrepancy between bundled and schema
repository versions of the XML Schema files, the schema repository shall be
considered authoritative.

The following normative documents contain provisions that, through reference in
this text, constitute provisions of this specification. For dated references,
subsequent amendments to, or revisions of, any of these publications do not
apply. For undated references, the latest edition of the normative document
referred to applies.

OGC 06-121r9, _OGC Web Services Common Standard_, version 2.0

OGC 09-146r2, _GML 3.2.1 Application Schema for Coverages_, version 1.0 +
Conformance classes used: gml-coverage

OGC 09-110r4, OGC® _Web Coverage Service 2.0 Interface Standard Core_,
version 2.0 +
Conformance classes used: core

OGC 11-053, OGC® _WCS 2.0 Interface Standard - CRS Service Model Extension_,
version 1.0 +
Conformance classes used: crs

OGC 12-039, OGC® _WCS 2.0 Interface Standard - Scaling Service Model Extension_,
version 1.0 +
Conformance classes used: scaling

OGC 12-040, OGC® _WCS 2.0 Interface Standard - Range Subsetting Service Model
Extension_, version 1.0 +
Conformance classes used: range-subsetting

OGC 12-049, OGC® _WCS 2.0 Interface Standard - Interpolation Service Model
Extension_, version 1.0 +
Conformance classes used: interpolation

OGC 09-147r3, OGC® _WCS 2.0 Interface Standard - KVP Protocol Binding
Extension_, version 1.0 +
Conformance classes used: get-kvp

OGC 09-149r1, OGC® _WCS 2.0 Interface Standard - SOAP Protocol Binding
Extension_, version 1.0 +
Conformance classes used: soap

OGC 12-100r1, OGC® _GML Application Schema - Coverages - GeoTIFF Coverage
Encoding Profile_, version 1.0 +
Conformance classes used: geotiff-coverage

OGC 11-010, OGC® _WCS 2.0 Interface Standard - NetCDF Encoding Format
Extension_, version 1.0 +
Conformance classes used: netcdf

OGC 11-011, OGC® _WCS 2.0 Interface Standard - JPEG2000 Encoding Format
Extension_, version 1.0 +
Conformance classes used: jpeg2000

OGC 10-157r3, _Earth Observation Metadata Profile of Observations and
Measurements_ +
Conformance classes used: eop, sar, opt

NOTE: Annex B lists transitional provisions until all of the above
specifications are available as adopted OGC documents.

== Terms and definitions

For the purposes of this document, the terms and definitions given in the above references
apply. In addition, the following terms and definitions apply. An arrow "->" indicates that the following term is defined in this Clause.

=== Coverage

digital representation of a spatio-temporally varying phenomenon as defined in
[OGC 09-146r2]

=== Dataset

2-D -> EO Coverage

NOTE: A Dataset usually represents observations obtained by satellite
instruments.

=== Dataset Series

collection of -> EO Coverages

=== EO Coverage

Rectified Grid -> Coverage or Referenceable Grid -> Coverage having an -> EO
Metadata record and a WGS84 bounding box

=== EO Metadata

-> EO Coverage’s metadata record

=== Stitched Mosaic

-> EO Coverage composed from subsets of one or more co-referenced -> Datasets

=== Lineage record

Data structure documenting an operation that has been applied to the -> coverage
it is part of

=== refers to

contains, in its -> EO Metadata element as defined in [OGC 10-157r3], the -> EO
Metadata element of

== Conventions

=== UML notation

Unified Modeling Language (UML) static structure diagrams appearing in this
specification are used as described in Subclause 5.2 of OGC Web Services Common
[OGC 06-121r9].

=== Data dictionary tables

The UML model data dictionary is specified herein in a series of tables. The
contents of the columns in these tables are described in Subclause 5.5 of [OGC
06-121r9]. The contents of these data dictionary tables are normative, including
any table footnotes.

=== Namespace prefix conventions

The following namespaces are used in this document. The prefix abbreviations
used constitute conventions used here, but are *not* normative. The namespaces
to which the prefixes refer are normative, however.

[#namespace_mappings,reftext='{table-caption} {counter:table-num}']
.Namespace mappings
[cols="^1,2*4",options="header"]
|===============================================================================
|Prefix |Namespace URI                        |Description
|xsd    |http://www.w3.org/2001/XMLSchema     |XML Schema namespace
|ows    |http://www.opengis.net/ows/2.0       |OWS Common 2.0
|gml    |http://www.opengis.net/gml/3.2       |GML 3.2.1
|gmlcov |http://www.opengis.net/gmlcov/1.0    |GML Application Schema for
Coverages 1.0
|wcs    |http://www.opengis.net/wcs/2.0       |WCS 2.0
|eop    |http://www.opengis.net/eop/2.0       |Earth Observation Metadata
Profile of Observations and Measurements
|opt    |http://www.opengis.net/opt/2.0       |Optical Earth Observation
Metadata Profile of Observations and Measurements (extension of eop)
|sar    |http://www.opengis.net/sar/2.0       |SAR Earth Observation Metadata
Profile of Observations and Measurements (extension of eop)
|wcseo  |http://www.opengis.net/wcs/wcseo/1.0 |WCS Application Profile - Earth
Observation 1.0
|===============================================================================

=== Multiple representations

When multiple representations of the same information are given in a
specification document these are consistent. Should this not be the case then
this is considered an error, and the XML schema shall take precedence.
