[#protocol_bindings,reftext='9']
== Protocol Bindings

=== Protocol choices

At least one of the protocols, GET/KVP and SOAP shall be supported by an
implementation. This choice is represented in this specification by two separate
conformance classes, _eowcs_get-kvp_ and _eowcs_soap_ defined in the Subclauses
below.

[requirement,uri="/req/eowcs/protocol-bindings"]
Implementations of this EO-WCS *shall* support at least one of the requirements
classes _eowcs_get-kvp_ and _eowcs_soap_. +
*Dependency*:
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.0/conf/eowcs_get-kvp,
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.0/conf/eowcs_soap

=== GET-KVP protocol conformance class

==== WCS GET/KVP encoding

[requirement,uri="/req/eowcs_get-kvp/mandatory"]
Implementations of this EO-WCS which support the _eowcs_get-kvp_ requirements
class *shall* support the WCS 2.0 protocol extension GET/KVP [OGC 09-147r3]. +
*Dependency*:
http://www.opengis.net/spec/WCS_protocol-binding_get-kvp/1.0/conf/get-kvp

[requirement,uri="/req/eowcs_get-kvp/conformance-class-in-profile"]
Implementations of this EO-WCS which support the _eowcs_get-kvp_ requirements
class *shall* include the following URI in a `Profile` element in the
`ServiceIdentification` in a _GetCapabilities_ response:
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.0/conf/eowcs_get-kvp

==== _DescribeEOCoverageSet_ GET/KVP encoding

[requirement,uri="/req/eowcs_get-kvp/describeEOCoverageSet-request"]
The `request` parameter in the `DescribeEOCoverageSet` request parameter of a
_DescribeEOCoverageSet_ request *shall* be indicated as follows: +
`request=DescribeEOCoverageSet`

[requirement,uri="/req/eowcs_get-kvp/describeEOCoverageSet-eoid"]
The `eoId` parameter in the `DescribeEOCoverageSet` request parameter of a
_DescribeEOCoverageSet_ request *shall* be indicated as follows, for parameter
values _v~1~, ..., v~n~_: +
`eoid=v~1~,...,v~n~`

[requirement,uri="/req/eowcs_get-kvp/describeEOCoverageSet-containment"]
The `containment` parameter in the `DescribeEOCoverageSet` request parameter of
a _DescribeEOCoverageSet_ request *shall* be indicated as follows: +
`containment=overlaps` +
or +
`containment=contains`

[requirement,uri="/req/eowcs_get-kvp/describeEOCoverageSet-subset"]
The `trim` parameters in the `DescribeEOCoverageSet` request parameter of a
_DescribeEOCoverageSet_ request *shall* be indicated through a possibly empty
set of subset specifications, each one with key \"``subset``" and value
specification given by a `SubsetSpec` adhering to this EBNF syntax <<3>>
and the resp. XML definitions <<6>>: +
`SubsetSpec: dimension [underline]#(# interval [underline]#)#` +
`dimension: [underline]#long# | [underline]#lat# | [underline]#phenomenonTime#` +
`interval: low [underline]#,# high` +
`low: point | [underline]#\*#` +
`high: point | [underline]#*#` +
`point: number | [underline]#"# token [underline]#"#` // [underline]#"# = ASCII 0x42

Syntax follows the http standard <<3>>: underlined tokens represent
literals which appear "as is" ("terminal symbols"), other tokens represent sub-
expressions to be substituted ("non-terminals"). A vertical bar ("|"") denotes
alternatives, items in brackets ("[ ]") are optional. Non-terminals `NCName`,
`number`, `token`, and `anyURI` follow the resp. XML definitions
<<6>>.

NOTE: Allowed values for points are determined by the CRS used. This ranges from
"2009-11-06" for time to "-41.5" and "41°5'" for lat/long whereby non-numeric
values have to be enclosed in double quotes.

NOTE: CRSs are fixed to WGS84 for space and ISO 8601 for time; still they need
to be indicated in the request syntax to keep it in sync with WCS Core trimming.

NOTE: As per http <<3>>, keys are case insensitive whereas values are
case sensitive.

Example: The following KVP-encoded _DescribeEOCoverageSet_ request addresses
service `path` on server `www.myservice.org` at port `port` requests coverage
`C0002` in the domain specified by the bounding box with longitude (-71,47) and
latitude (-66,51), expressed in spatial CRS WGS84-2D and temporal CRS ISO:8601
(which are assumed to be supported for the coverage):

    http://www.myserver.org:port/path?
    service=WCS
    &version=2.0.1
    &request=DescribeEOCoverageSet
    &eoid=C0002
    &containment=overlaps
    &subset=long(-71,47)
    &subset=lat(-66,51)
    &subset=phenomenonTime( " 2009-11-06T23:20:52Z "," 2009-11-13T23:20:52Z " )

=== SOAP protocol conformance class

==== WCS SOAP encoding

[requirement,uri="/req/eowcs_soap/mandatory"]
Implementations of this EO-WCS which support the _eowcs_soap_ requirements class
*shall* support the WCS 2.0 protocol extension SOAP [OGC 09-149r1]. +
*Dependency*:
http://www.opengis.net/spec/WCS_protocol-binding_soap/1.0/conf/soap

[requirement,uri="/req/eowcs_soap/conformance-class-in-profile"]
Implementations of this EO-WCS which support the _eowcs_soap_ requirements class
*shall* include the following URI in a `Profile` element in the
`ServiceIdentification` in a _GetCapabilities_ response:
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.0/conf/eowcs_soap

==== _DescribeEOCoverageSet_ SOAP encoding

[requirement,uri="/req/eowcs_soap/describeEOCoverageSet-request-structure"]
A _DescribeEOCoverageSet_ request *shall* contain exactly one `Body` element
containing exactly one `DescribeEOCoverageSet` element.

[requirement,uri="/req/eowcs_soap/describeEOCoverageSet-response-structure"]
In the response to a successful _DescribeEOCoverageSet_ request, the SOAP
`Envelope` *shall* contain exactly one `Body` element which contains a
`EOWCS::EOCoverageSetDescription` as its single element.

Example: See files `wcseo_requestDescribeEOCoverageSet.xml` and
`wcseo_responseDescribeEOCoverageSet.xml` being part of this standard.

==== _DescribeEOCoverageSet_ WSDL

[requirement,uri="/req/eowcs_soap/wsdl"]
Publication of a WCS SOAP service endpoint *shall* use the binding as defined
in file `wsdl/wcs-soap-binding.wsdl` of the EO-WCS package.

NOTE: A sample service description relying on this binding is provided in file
`example-soap-endpoint.wsdl`.
