:doctype: book
:linkcss:
:toc2:
:toclevels: 3
:toc-placement!:
:toc-title: Contents
:appendix-caption: Annex
:requirement-caption: Requirement
:icons: font
:source-highlighter: coderay
:numbered!:

[id="ogcname"]
Open Geospatial Consortium +
[id="ogcheading"]
Publication Date: TBD +
Approval Date: TBD +
Submission Date: TBD +
Reference number of this Document: OGC 10-140r1 +
External reference for this OGC® document: http://www.opengis.net/doc/IS/WCS-application-profile-earth-observation/1.0 +
URL for this OGC® document: https://eox-a.github.io/eo-wcs/ +
Version: 1.1draft +
Category: OGC® Interface Standard +
Editor: Peter Baumann, Stephan Meissl, Jinsongdi Yu

[title]
= OGC® Web Coverage Service 2.0 Interface Standard - Earth Observation Application Profile

Copyright © 2014, 2016 Open Geospatial Consortium. +
To obtain additional rights of use, visit http://www.opengeospatial.org/legal/ +

*Warning*

This document is an OGC Member approved international standard. This document is
available on a royalty free, non-discriminatory basis. Recipients of this
document are invited to submit, with their comments, notification of any
relevant patent rights of which they are aware and to provide supporting
documentation.

Document type:          OGC Implementation Standard +
Document subtype:       Interface +
Document stage:         Draft update of Approved version +
Document language:      English +

== License Agreement

Permission is hereby granted by the Open Geospatial Consortium, ("Licensor"),
free of charge and subject to the terms set forth below, to any person obtaining
a copy of this Intellectual Property and any associated documentation, to deal
in the Intellectual Property without restriction (except as set forth below),
including without limitation the rights to implement, use, copy, modify, merge,
publish, distribute, and/or sublicense copies of the Intellectual Property, and
to permit persons to whom the Intellectual Property is furnished to do so,
provided that all copyright notices on the intellectual property are retained
intact and that each person to whom the Intellectual Property is furnished
agrees to the terms of this Agreement.

If you modify the Intellectual Property, all copies of the modified Intellectual
Property must include, in addition to the above copyright notice, a notice that
the Intellectual Property includes modifications that have not been approved or
adopted by LICENSOR.

THIS LICENSE IS A COPYRIGHT LICENSE ONLY, AND DOES NOT CONVEY ANY RIGHTS UNDER
ANY PATENTS THAT MAY BE IN FORCE ANYWHERE IN THE WORLD.

THE INTELLECTUAL PROPERTY IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT OF THIRD
PARTY RIGHTS. THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE DO NOT
WARRANT THAT THE FUNCTIONS CONTAINED IN THE INTELLECTUAL PROPERTY WILL MEET YOUR
REQUIREMENTS OR THAT THE OPERATION OF THE INTELLECTUAL PROPERTY WILL BE
UNINTERRUPTED OR ERROR FREE. ANY USE OF THE INTELLECTUAL PROPERTY SHALL BE MADE
ENTIRELY AT THE USER'S OWN RISK. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR ANY
CONTRIBUTOR OF INTELLECTUAL PROPERTY RIGHTS TO THE INTELLECTUAL PROPERTY BE
LIABLE FOR ANY CLAIM, OR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES,
OR ANY DAMAGES WHATSOEVER RESULTING FROM ANY ALLEGED INFRINGEMENT OR ANY LOSS OF
USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR UNDER ANY
OTHER LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH THE IMPLEMENTATION,
USE, COMMERCIALIZATION OR PERFORMANCE OF THIS INTELLECTUAL PROPERTY.

This license is effective until terminated. You may terminate it at any time by
destroying the Intellectual Property together with all copies in any form. The
license will also terminate if you fail to comply with any term or condition of
this Agreement. Except as provided in the following sentence, no such
termination of this license shall require the termination of any third party
end-user sublicense to the Intellectual Property which is in force as of the
date of notice of such termination. In addition, should the Intellectual
Property, or the operation of the Intellectual Property, infringe, or in
LICENSOR's sole opinion be likely to infringe, any patent, copyright, trademark
or other right of a third party, you agree that LICENSOR, in its sole
discretion, may terminate this license without any compensation or liability to
you, your licensees or any other party. You agree upon termination of any kind
to destroy or cause to be destroyed the Intellectual Property together with all
copies in any form, whether held by you or by any third party.

Except as contained in this notice, the name of LICENSOR or of any other holder
of a copyright in all or part of the Intellectual Property shall not be used in
advertising or otherwise to promote the sale, use or other dealings in this
Intellectual Property without prior written authorization of LICENSOR or such
copyright holder. LICENSOR is and shall at all times be the sole entity that may
authorize you or any third party to use certification marks, trademarks or other
special designations to indicate compliance with any LICENSOR standards or
specifications.

This Agreement is governed by the laws of the Commonwealth of Massachusetts. The
application to this Agreement of the United Nations Convention on Contracts for
the International Sale of Goods is hereby expressly excluded. In the event any
provision of this Agreement shall be deemed unenforceable, void or invalid, such
provision shall be modified so as to make it valid and enforceable, and as so
modified the entire Agreement shall remain in full force and effect. No
decision, action or inaction by LICENSOR shall be construed to be a waiver of
any rights or remedies available to it. None of the Intellectual Property or
underlying information or technology may be downloaded or otherwise exported or
reexported in violation of U.S. export laws and regulations. In addition, you
are responsible for complying with any local laws in your jurisdiction which may
impact your right to import, export or use the Intellectual Property, and you
represent that you have complied with any regulations or registration procedures
required by applicable law to make this license enforceable

toc::[]

== Abstract

The OGC _Web Coverage Service (WCS) Application Profile - Earth Observation_
(EO- WCS), defines a profile of WCS 2.0 [OGC 09-110r4] for use on Earth
Observation data.

Suggested additions, changes, and comments on this draft document are welcome
and encouraged. Such suggestions may be submitted by email message or by making
suggested changes in an edited copy of this document.

== Keywords

ogcdoc, wcs, profile, eo, earth observation, dataset, dataset series, stitched
mosaic

== Terms and definitions

This document uses the standard terms defined in Subclause 5.3 of [OGC
06-121r9], which is based on the ISO/IEC Directives, Part 2, Rules for the
structure and drafting of International Standards. In particular, the word
"shall" (not "must") is the verb form used to indicate a requirement to be
strictly followed to conform to this standard.

== Submitting organizations

The following organizations have submitted this Interface Specification to the
Open GeoSpatial Consortium, Inc.:

* Jacobs University Bremen
* EOX IT Services GmbH
* G.I.M. Geographic Information Management nv/sa
* European Space Agency (ESA)
* Spot Image

Additionally, rasdaman GmbH has made substantial contributions.

== Document Contributor Contact Points

[options="header"]
|===============================================================================
|Name                                   |Organization
|Peter Baumann                          |Jacobs University Bremen, rasdaman GmbH
|Jinsongdi Yu                           |Jacobs University Bremen
|Stephan Meissl <stephan.meissl@eox.at> |https://eox.at[EOX IT Services GmbH]
|Christian Schiller                     |https://eox.at[EOX IT Services GmbH]
|===============================================================================

== Changes to the OGC ® Abstract Specification

The OGC ® Abstract Specification does not require any changes to accommodate the
technical contents of this (part of this) document.

== Future Work

Among the topics for future development are the following items:

* Allow additional coverage representations (i.e., "multipart" and "special
format" coverage encodings) once these are adopted for the GML Application
Schema for Coverages [OGC 09-146].

* Extend the current 2-D EO Coverage footprint to 3-D footprints by extending
  them with elevation; this will involve extending footprints from bounding
  multi-curves (polygons) to multi-surfaces.

* Specify usage and content of `EOWCS::Lineage` in more detail.

* Align with forthcoming WCS 2.0 extensions once available.

* Add paging mechanism similar to WFS 2.0.

include::0_introduction.adoc[]

:numbered:

include::1_base.adoc[]
include::2_data-model.adoc[]
include::3_service-model.adoc[]
include::4_wcs-extensions.adoc[]
include::5_protocol-bindings.adoc[]

:numbered!:

include::bibliography.adoc[]

:numbered:

include::annexes/a_ats.adoc[]
include::annexes/b_transitional-provisions.adoc[]
include::annexes/c_use-case-examples.adoc[]
include::annexes/d_revision-history.adoc[]
