[appendix]
== (normative) Abstract test suite

A WCS implementation must satisfy the following system characteristics to be
conformant with this specification.

=== Conformance Test Class: eowcs

The OGC URI identifier of this conformance class is:
http://www.opengis.net/spec/WCS/2.0/conf/WCS_application-profile_eowcs/1.0/conf/eowcs.

Tests identifiers below are relative to
http://www.opengis.net/spec/WCS/2.0/WCS_application-profile_eowcs/1.0/.

==== EO Metadata

*Test id: /conf/eowcs/eo-metadata-structure*

*Test Purpose: <<_requirement-1>>*

*Test method:*

For each EO Coverage offered by the server under test:

* retrieve coverage information via _DescribeCoverage_, _DescribeEOCoverageSet_,
  and _GetCoverage_ operations.
* Check that the responses contain a `EOWCS::EOMetadata` corresponding to the
  definition and that all responses contain the same information.

Test passes if all individual tests pass.

==== Footprint in EO Metadata

*Test id: /conf/eowcs/footprint-in-eo-metadata*

*Test Purpose: <<_requirement-2>>*

*Test method:*

For each EO Coverage offered by the server under test:

* retrieve coverage information via _DescribeCoverage_, _DescribeEOCoverageSet_,
  and _GetCoverage_ operations.
* Check that the responses contain an
  `eop:EarthObservation/om:featureOfInterest/eop:Footprint` element in the
  `EOWCS::EOMetadata` and that all responses contain the same information.

Test passes if all individual tests pass.

==== EO Coverage

*Test id: /conf/eowcs/eo-coverage-structure*

*Test Purpose: <<_requirement-3>>*

*Test method:*

For each EO Coverage offered by the server under test:

* retrieve coverage information via _GetCoverage_ operation.
* Check that all responses consist of an XML document as defined in the places
  referenced.

Test passes if all individual tests pass.

==== EO Metadata in EO Coverage

*Test id: /conf/eowcs/eo-metadata-in-eo-coverage*

*Test Purpose: <<_requirement-4>>*

*Test method:*

For each EO Coverage offered by the server under test:

* retrieve coverage information via _DescribeCoverage_, _DescribeEOCoverageSet_,
  and _GetCoverage_ operations.
* Check that the responses contain a `EOWCS::EOMetadata` and that all responses
  contain the same information.

Test passes if all individual tests pass.

==== EOP Identifier in EO Metadata

*Test id: /conf/eowcs/eop-identifier-in-eo-metadata*

*Test Purpose: <<_requirement-5>>*

*Test method:*

For each EO Coverage offered by the server under test:

* retrieve coverage information via _DescribeCoverage_, _DescribeEOCoverageSet_,
  and _GetCoverage_ operations.
* Check that the responses contain an
  `eop:EarthObservation/eop:metadataProperty/eop:EarthObservationMetaData/eop:identifier`
  whose first word is identical to the EO Coverage identifier.

Test passes if all individual tests pass.

==== Footprint inside BoundedBy

*Test id: /conf/eowcs/footprint-inside-boundedBy*

*Test Purpose: <<_requirement-6>>*

*Test method:*

For each EO Coverage offered by the server under test:

* retrieve coverage information via _DescribeCoverage_, _DescribeEOCoverageSet_,
  and _GetCoverage_ operations.
* Check that all polygons listed in
  `eop:EarthObservation/om:featureOfInterest/eop:Footprint` element are
  contained in the bounding box of the `gml:boundedBy` element of the
  `gml:Envelope`.

Test passes if all individual tests pass.

==== PhenomenonTime in EO Metadata

*Test id: /conf/eowcs/phenomenonTime-in-eo-metadata*

*Test Purpose: <<_requirement-7>>*

*Test method:*

For each EO Coverage offered by the server under test:

* retrieve coverage information via _DescribeCoverage_, _DescribeEOCoverageSet_,
  and _GetCoverage_ operations.
* Check that the responses contain elements
  `eop:EarthObservation/om:phenomenonTime/gml:TimePeriod/gml:beginPosition` and
  `eop:EarthObservation/om:phenomenonTime/gml:TimePeriod/gml:endPosition` where
  `beginPosition ≤ endPosition`.

Test passes if all individual tests pass.

==== PhenomenonTime ISO9891

*Test id: /conf/eowcs/phenomenonTime-iso8601*

*Test Purpose: <<_requirement-8>>*

*Test method:*

For each EO Coverage offered by the server under test:

* retrieve coverage information via _DescribeCoverage_, _DescribeEOCoverageSet_,
  and _GetCoverage_ operations.
* Check that the temporal validity values are expressed in ISO 8601.

Test passes if all individual tests pass.

==== Rangeset of Coverage

*Test id: /conf/eowcs/range-set-of-eo-coverage*

*Test Purpose: <<_requirement-9>>*

*Test method:*

For each EO Coverage offered by the server under test:

* retrieve coverage information via _GetCoverage_ operation.
* Check that all cells, whose locations are outside the EO Metadata footprint
  when both are evaluated in WGS84, contain some nil value as defined in the
  bounding EO Coverage’s range type.

Test passes if all individual tests pass.

==== Dataset Structure

*Test id: /conf/eowcs/dataset-structure*

*Test Purpose: <<_requirement-10>>*

*Test method:*

For each EO Dataset offered by the server under test:

* retrieve coverage information via _GetCoverage_ operation.
* Check that all responses consist of an XML document as defined in the places
  referenced.

Test passes if all individual tests pass.

==== Referenceable Stitched Mosaic-structure

*Test id: /conf/eowcs/referenceableStitchedMosaic-structure*

*Test Purpose: <<_requirement-11>>*

*Test method:*

For each `EOWCS::ReferenceableStitchedMosaic` offered by the server under test:

* retrieve coverage information via _GetCoverage_ operation.
* Check that all responses consist of an XML document of type
  `EOWCS::ReferenceableStitchedMosaic` as described in the references stated by
  the requirement.

Test passes if all individual tests pass.

==== Rectified Stitched Mosaic-structure

*Test id: /conf/eowcs/rectifiedStitchedMosaic-structure*

*Test Purpose: <<_requirement-12>>*

*Test method:*

For each `EOWCS::RectifiedStitchedMosaic` offered by the server under test:

* retrieve coverage information via _GetCoverage_ operation.
* Check that all responses consist of an XML document of type
  `EOWCS::RectifiedStitchedMosaic` as described in the references stated by the
  requirement.

Test passes if all individual tests pass.

==== Composed-of in Stitched mosaic

*Test id: /conf/eowcs/composedOf-in-stitched-mosaic*

*Test Purpose: <<_requirement-13>>*

*Test method:*

For each `EOWCS::RectifiedStitchedMosaic` and `EOWCS::RectifiedStitchedMosaic`
offered by the server under test:

* Obtain the set of `dataset` identifiers contained in
  `eop:EarthObservation/eop:metaDataProperty/eop:EarthObservationMetaData/eop:composedOf`
   via _DescribeCoverage_, _DescribeEOCoverageSet_, and _GetCoverage_
   operations.
* Check that all responses contain the same identifier information.
* Obtain the contained set of dataset identifiers of the Stitched Mosaic. Check
  that all responses contain the same identifier information.
* If the `eop:composedOf` element is present then check that the contained set
  of `dataset` identifiers in
  `eop:EarthObservation/eop:metaDataProperty/eop:EarthObservationMetaData/eop:composedOf`
  is equal to the set of `dataset` identifiers of the Stitched Mosaic.

Test passes if all individual tests pass.

==== Contributing Footprint inside Footprint

*Test id: /conf/eowcs/contributingFootprint-inside-footprint*

*Test Purpose: <<_requirement-14>>*

*Test method:*

For each Stitched Mosaic offered by the server under test:

* retrieve coverage information via _DescribeCoverage_, _DescribeEOCoverageSet_,
  and _GetCoverage_ operations.
* For each obtained `dataset` _d_:
** obtain the contributingFootprint associated with the reference to _d_ and
   check that all responses contain the same contributingFootprint information
   with the reference to _d_.
** obtain the footprint of _d_ coverage via _DescribeCoverage_,
   _DescribeEOCoverageSet_, and _GetCoverage_ operations, and check that all
   responses contain the same footprint information.
** Check that the contributingFootprint associated with the reference to _d_ is
   contained in the footprint of _d_.

Test passes if all individual tests pass.

==== Contributing Footprint-pairwise-disjoint

*Test id: /conf/eowcs/contributinFootprint-pairwise-disjoint*

*Test Purpose: <<_requirement-15>>*

*Test method:*

For each Stitched Mosaic offered by the server under test:

* retrieve coverage information via _DescribeCoverage_, _DescribeEOCoverageSet_,
  and _GetCoverage_ operations. Check that all responses contain the same
  contributingFootprint information.
* Check that the contributingFootprints are pair-wise disjoint.

Test passes if all individual tests pass.

==== Contributing Footprint-union-of-footprints

*Test id: /conf/eowcs/contributingFootprint-union-of-footprints*

*Test Purpose: <<_requirement-16>>*

*Test method:*

For each Stitched Mosaic offered by the server under test:

* retrieve coverage information via _DescribeCoverage_, _DescribeEOCoverageSet_,
  and _GetCoverage_ operations.
* Check that there is a contributingFootprint for each dataset of the Stitched
  Mosaic.

Test passes if all individual tests pass.

==== Dataset Domain Set in Set in Stitched Mosaic Domain Set

*Test id: /conf/eowcs/dataset-domain-set-in-stitched-mosaic-domain-set*

*Test Purpose: <<_requirement-17>>*

*Test method:*

For each Stitched Mosaic offered by the server under test:

* Obtain all cells of _s_ as defined by domain set of _s_ via _GetCoverage_
  operation.
* For each obtained `dataset` _d_:
** Obtain all cells of _d_ as defined by domain set of _d_ via _GetCoverage_
   operation.
** Check that all cells of _d_ as defined by domain set of _d_ are included in
   the set of all cells of _s_ as defined by domain set of _s_.

Test passes if all individual tests pass.

==== Datasets in Rectified Stitched Mosaic Same Offset Vector

*Test id: /conf/eowcs/datasets-in-rectifiedStitcheMosaic-same-offsetVector*

*Test Purpose: <<_requirement-18>>*

*Test method:*

For each Rectified Stitched Mosaic offered by the server under test:

* For each obtained `dataset` _d_:
** retrieve coverage information via _DescribeCoverage_,
   _DescribeEOCoverageSet_, and _GetCoverage_ operations.
** Check that all responses contain the same `gml:offsetVector` information in
   their domain sets.
* Check that all Datasets have identical values in the `gml:offsetVector`
  elements of their domain sets.

Test passes if all individual tests pass.

==== Rectified Stitched Mosaic OffsetVector

*Test id: /conf/eowcs/rectifiedStitchedMosaic-offsetVector*

*Test Purpose: <<_requirement-19>>*

*Test method:*

For each Rectified Stitched Mosaic offered by the server under test:

* retrieve the value of the `gml:offsetVector` elements of the domain set via
  _DescribeCoverage_, _DescribeEOCoverageSet_, and _GetCoverage_ operations.
* Check that all responses contain the same `offsetVector` information.
* For each obtained `dataset` _d_:
** retrieve coverage information via _DescribeCoverage_,
   _DescribeEOCoverageSet_, and _GetCoverage_ operations.
** Check that all responses contain the same `gml:offsetVector` information in
   their domain sets.
* Check that both the Rectified Stitched Mosaic and the Datasets the Rectified
  Stitched Mosaic refers to have identical values in the `gml:offsetVector`
  elements of their domain sets.

Test passes if all individual tests pass.

==== Referenceable Stitched Mosaic Domainset

*Test id: /conf/eowcs/referenceableStitchedMosaic-domain-set*

*Test Purpose: <<_requirement-20>>*

*Test method:*

For each Referenceable Stitched Mosaic offered by the server under test:

* For any pair _d~1~_ and _d~2~_ of Datasets referred to by the given Stitched
  Mosaic:
** Check that the set of point locations in the geographic overlap of the _d~1~_
   and _d~2~_ domain set are identical.

Test passes if all individual tests pass.

==== Temporal Validity Stitched Mosaic

*Test id: /conf/eowcs/temporal-validity-stitched-mosaic*

*Test Purpose: <<_requirement-21>>*

*Test method:*

For each Stitched Mosaic offered by the server under test:

* retrieve the time interval _t_ of the Stitched Mosaic given by its
  `eop:EarthObservation/om:phenomenonTime/gml:TimePeriod/gml:beginPosition` and
  `eop:EarthObservation/om:phenomenonTime/gml:TimePeriod/gml:endPosition`
  elements in `eowcs:EOMetadata` via _DescribeCoverage_,
  _DescribeEOCoverageSet_, and _GetCoverage_ operations.
* Check that all responses contain the same time interval information. +
For each obtained dataset _d_:
** retrieve the time interval _t~i~_ of `dataset` _d_ given by its
   `eop:EarthObservation/om:phenomenonTime/gml:TimePeriod/gml:beginPosition` and
   `eop:EarthObservation/om:phenomenonTime/gml:TimePeriod/gml:endPosition`
   elements in `eowcs:EOMetadata` via _DescribeCoverage_,
   _DescribeEOCoverageSet_, and _GetCoverage_ operations.
** Check that all responses contain the same time interval information.
* Check that _t_ is the minimal time interval containing the temporal validities
  of all Datasets the Stitched Mosaic refers to.

Test passes if all individual tests pass.

==== Datasets in Stitched Mosaic Same Rangetype

*Test id: /conf/eowcs/datasets-in-stitched-mosaic-same-range-type*

*Test Purpose: <<_requirement-22>>*

*Test method:*

For each Stitched Mosaic offered by the server under test:

* Obtain range type via _DescribeCoverage_, _DescribeEOCoverageSet_, and
  _GetCoverage_ operations. Check that all responses contain the same range type
  information _s_.
* For each obtained `dataset`:
** Obtain range type via _DescribeCoverage_, _DescribeEOCoverageSet_, and
   _GetCoverage_ operations.
** Check that all responses contain the same range type _d_, and check that _d_
   is identical to the range type of _s_.

Test passes if all individual tests pass.

==== Nil Values in Stitched Mosaic

*Test id: /conf/eowcs/nil-values-in-stitched-mosaic*

*Test Purpose: <<_requirement-23>>*

*Test method:*

For each Stitched Mosaic offered by the server under test:

* Obtain the domain set via _DescribeCoverage_, _DescribeEOCoverageSet_, and
  _GetCoverage_ operations.
* Check that all responses contain the same domain set information.
* Check that if the domain set contains locations which are not inside any
  contributingFootprint the Stitched Mosaic refers to then the nil value set of
  that Stitched Mosaic are not empty.

Test passes if all individual tests pass.

==== Range Values of Stitched Mosaic

*Test id: /conf/eowcs/range-values-of-stitched-mosaic*

*Test Purpose: <<_requirement-24>>*

*Test method:*

For each Stitched Mosaic offered by the server under test:

* Obtain the contained cells via _GetCoverage_ operation.
* For each obtained cell with location _p_ check that:
** if _p_ is located within the contributingFootprint of some Dataset _d_
   referred to by _s_ then it is the range value of _d_ at _p_;
** if _p_ is not located within the contributingFootprint of any Dataset _d_
   referred to by _s_ then it is one of the range values contained in the nil
   value set of _s_.

Test passes if all individual tests pass.

==== Dataset Series Structure

*Test id: /conf/eowcs/datasetSeries-structure*

*Test Purpose: <<_requirement-25>>*

*Test method:*

For each `EOWCS::DatasetSeries` offered by the server under test:

* Obtain the `EOWCS::DatasetSeries` via _DescribeEOCoverageSet_. Check that all
  responses consist of an XML document as defined in the places referenced.

Test passes if all individual tests pass.

==== Footprint in Dataset Series

*Test id: /conf/eowcs/footprint-in-datasetSeries*

*Test Purpose: <<_requirement-26>>*

*Test method:*

For each EOWCS::DatasetSeries offered by the server under test:
* Obtain the footprint of EOWCS::DatasetSeries via DescribeEOCoverageSet.
* Check that the locations of the footprint are expressed in WGS84.
* Obtain the footprints of all Stitched Mosaics and Datasets the Dataset Series refers to.
* Check that these footprints are enclosed in the footprint of EOWCS::DatasetSeries.
Test passes if all individual tests pass.

==== TimePeriod in DatasetSeries

*Test id: /conf/eowcs/timePeriod-in-datasetSeries*

*Test Purpose: <<_requirement-27>>*

*Test method:*

For each EOWCS::DatasetSeries offered by the server under test:
* Obtain the timePeriod element s of EOWCS::DatasetSeries via DescribeEOCoverageSet. Check that s is expressed in ISO 8601and that:
* For each Stitched Mosaics and Datasets the Dataset Series refers to:
** retrieve the time interval d via DescribeCoverage, DescribeEOCoverageSet, and GetCoverage operations. Check that all responses contain the same time interval information.
** Check that d is enclosed by the temporal validities of s.
Test passes if all individual tests pass.

==== No circular references of Dataset Series

*Test id: /conf/eowcs/nocircularreference-of-datasetSeries*

*Test Purpose: <<_requirement-28>>*

*Test method:*

For each EOWCS::DatasetSeries offered by the server under test:
* Obtain the EOWCS::DatasetSeries via DescribeEOCoverageSet. Check that all EOWCS::DatasetSeries it refferes to do not refer to the EOWCS::DatasetSeries at hand.
Test passes if all individual tests pass.

==== GetCapabilities Request Sections

*Test id: /conf/eowcs/getCapabilities-request-sections*

*Test Purpose: <<_requirement-29>>*

If a GetCapabilities request contains an ows:Sections element then this element shall contain ows:Section elements with the values defined in OWS Common, or “DatasetSeriesSummary”, or “CoverageSummary”.
Dependency: [OGC 06-121r9] clause 7.3.3
Test method:    Send a valid GetCapabilities request contains a sections element and this element contains section elements with the values defined in OWS Common, or “DatasetSeriesSummary”, or “CoverageSummary” to the server under test, check the result consists of an XML document of type Capabilities and the appropriate components, as defined in the plac-es referenced.

==== GetCapabilities Response Conformance Class in Profile

*Test id: /conf/eowcs/getCapabilities-response-conformance-class-in-profile*

*Test Purpose: <<_requirement-30>>*

A WCS service implementing this extension shall include the following URI in a Profile element in the ServiceIdentification in a GetCapabilities response:
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.0/conf/eowcs
Test method:    Determine the list of supported extensions via a valid GetCapabilities re-quest; check that the extension required is listed.

==== GetCapabilities Response Structure

*Test id: /conf/eowcs/getCapabilities-response-structure*

*Test Purpose: <<_requirement-31>>*

The response to a successful GetCapabilities request shall consist of a data structure as defined in Figure 7, Table 7, and the XML Schema being part of this standard.
Dependency: [OGC 09-110r4] Clause 8 (http://www.opengis.net/doc/IS/wcs-core-2.0.1/clause/8)
Test method:    Send a valid GetCapabilities request to the server under test, check the result consists of an XML document of type Capabilities and the appropriate components, as defined in the places referenced.

==== GetCapabilities Response DatasetSeriesSummary

*Test id: /conf/eowcs/getCapabilities-response- datasetSeriesSummary*

*Test Purpose: <<_requirement-32>>*

*Test method:*

Send a valid GetCapabilities request to the service under test. If a EOWCS::DatasetSeriesSummary section is contained in the re-sponse then send, for each DatasetSeriesId, a valid DescribeEOCoverag-eSet request. Check that none of these requests results in an exception. Test passes if all checks are successful.

==== GetCapabilities Response DatasetSeriesSummary no-duplicates

*Test id: /conf/eowcs/ getCapabilities-response-datasetSeriesSummary-no-duplicates*

*Test Purpose: <<_requirement-33>>*

*Test method:*

Send a valid GetCapabilities request to the service under test. If a EOWCS::DatasetSeriesSummary section is contained in the re-sponse check that it does not contain any duplicate Dataset Series identifi-er.

==== GetCapabilities Response Coverage Summary

*Test id: /conf/eowcs/getCapabilities-response-coverageSummary*

*Test Purpose: <<_requirement-34>>*

*Test method:*

Send a valid GetCapabilities request to the service under test. If a WCS::CoverageSummary section is contained in the response then send, for each coverage identifier, a valid DescribeCoverage and a valid DescribeEOCoverageSet request. Check that none of these requests re-sults in an exception. Test passes if all individual tests pass.

==== GetCapabilities Response Coverage Summary Section

*Test id: /conf/eowcs /getCapabilities-response-coverageSummary-section*

*Test Purpose: <<_requirement-35>>*

*Test method:*

Send valid GetCapabilities requests contains a sections parameter and the section parameter list contains one of the values “CoverageSummary”, “Contents”, or “All” to the service under test. Check that the response contains wcs:CoverageSummary elements.Test passes if all individual tests pass.

==== GetCapabilities Response DatasetSeries Summary Section

*Test id: /conf/eowcs/getCapabilities-response-datasetSeriesSummary-section*

*Test Purpose: <<_requirement-36>>*

*Test method:*

Send valid GetCapabilities requests contains a sections parameter and the section parameter list contains one of the values “DatasetSeriesSum-mary” or “All” to the service under test. Check that the response contains a eowcs:DatasetSeriesSummary.Test passes if all individual tests pass.

==== GetCapabilities Response Coverage Subtype

*Test id: /conf/eowcs/getCapabilities-response-coverageSubtype*

*Test Purpose: <<_requirement-37>>*

*Test method:*

Send a valid GetCapabilities request to the server under test, check that each EO Coverage listed contains the corresponding value in its WCS::CoverageSubtype element.

==== GetCapabilities Response countDefault

*Test id: /conf/eowcs/getCapabilities-response-countDefault*

*Test Purpose: <<_requirement-38>>*

*Test method:*

Send a valid GetCapabilities request to the server under test, check that its ows:OperationsMetadata element contains an ows:Constraint element, as defined in the places referenced.

==== Describe Coverage Response EO Metadata

*Test id: /conf/eowcs/describeCoverage-response-eo-metadata*

*Test Purpose: <<_requirement-39>>*

*Test method:*

For each EO Coverage offered by the server, send a valid DescribeCover-age request to server under test. Check that the result contains an EOMetadata element. Test passes if all individual tests pass.

==== Describe Coverage Response Coverage Subtype

*Test id: /conf/eowcs/describeCoverage-response-coverageSubtype*

*Test Purpose: <<_requirement-40>>*

*Test method:*

Send a valid DescribeCoverage request to the server under test, check that each EO Coverage listed contains the corresponding value in its WCS::CoverageSubtype element.

==== GetCoverage Request no Slicing

*Test id: /conf/eowcs/getCoverage-request-no-slicing*

*Test Purpose: <<_requirement-41>>*

*Test method:*

For each EO Coverage offered by the server:
* send otherwise GetCoverage requests with and without a slicing opera-tion.
* Check whether appropriate valid results or exceptions, resp., are deliv-ered.
Test passes if all individual tests pass.

==== GetCoverage Response Coverage Type

*Test id: /conf/eowcs/getCoverage-response-coverage-type*

*Test Purpose: <<_requirement-42>>*

The response to a successful GetCoverage request
- on a Rectified Stitched Mosaic shall be of type RectifiedStitchedMosaic,
- on a Rectified Dataset shall be of type RectifiedDataset,
- on a Referenceable Stitched Mosaic shall be of type Referencea-bleStitchedMosaic, and
- on a Referenceable Dataset shall be of type ReferenceableDataset,.
Test method:    For each Rectified EO Coverage offered by the server:
* send a valid GetCoverage request to server under test.
* Check that the result is Coverage of correct type.
Test passes if all individual tests pass.

==== GetCoverage Response EO Metadata

*Test id: /conf/eowcs/getCoverage-response-eo-metedata*

*Test Purpose: <<_requirement-43>>*

*Test method:*

For each EO Coverage offered by the server:
* send a valid GetCoverage request to server under test.
* Check that the responses contain a EOWCS::EOMetadata.
Test passes if all individual tests pass.

==== GetCoverage Response EO Metadata in Stitched Mosaic

*Test id: /conf/eowcs/getCoverage-response-eo-metedata-in-stitched-mosaic*

*Test Purpose: <<_requirement-44>>*

*Test method:*

For each Stitched Mosaic offered by the server:
* send a valid GetCoverage request with an effective spatio-temporal request trim interval to server under test.
* Check that the EOWCS::EOMetadata of the coverage returned con-tains the original Stitched Mosaic’s references to those Datasets which have a non-empty intersection with the effective spatio-temporal re-quest trim interval.
Test passes if all individual tests pass.

==== GetCoverage Response Footprint in EO Metadata

*Test id: /conf/eowcs/getCoverage-response-footprint-in-eo-metedata*

*Test Purpose: <<_requirement-45>>*

*Test method:*

For each EO Coverage offered by the server:
* Send a valid GetCoverage request with a spatial request trim interval to server under test. Check that the footprint of the EOWCS::EOMe-tadata in the coverage returned is given by the intersection of the spatial request interval and the footprint of the coverage requested.
* Send a valid GetCoverage request without a trimming interval to serv-er under test. Check that the footprint in the result coverage is given by the footprint of the coverage requested.
Test passes if all individual tests pass.

==== GetCoverage Response Lineage in EO Metadata

*Test id: /conf/eowcs/getCoverage-response-lineage-in-eo-metedata*

*Test Purpose: <<_requirement-46>>*

*Test method:*

For each EO Coverage offered by the server under test:
* retrieve Lineage component information via DescribeCoverage, DescribeEOCoverageSet, and GetCoverage operations. Check that all re-sponses contain the same information.
* Send a valid GetCoverage request to server under test. Check that the Lineage component  consists of the Lineage component of the cover-age requested with one record appended containing the complete, ver-batim GetCoverage  request leading to this response.
Test passes if all individual tests pass.

==== DescribeEOCoverageSet Request Structure

*Test id: /conf/eowcs/describeEOCoverageSet-request-structure*

*Test Purpose: <<_requirement-47>>*

*Test method:*

Send DescribeEOCoverageSet requests with valid and invalid request structure.
Pass test if appropriate valid results or exceptions, resp., are delivered.

==== DescribeEOCoverageSet Request Sections

*Test id: /conf/eowcs/describeEOCoverageSet-request-sections*

*Test Purpose: <<_requirement-48>>*

If a DescribeEOCoverageSet request contains an ows:Sections element then this element shall contain one of the values “CoverageDescriptions”, “DatasetSeriesDescriptions”, or “All”.
Dependency: [OGC 06-121r9] clause 7.3.3
Test method:    Send otherwise valid DescribeEOCoverageSet requets contain a sec-tions element and this element contains one of the values:
* “CoverageDescription”
* “DatasetSeriesDescriptions”
* “All”
* invalid values
Pass test if appropriate valid results or exceptions, resp., are delivered.

==== DescribeEOCoverageSet Request eoId

*Test id: /conf/eowcs/describeEOCoverageSet-request-eoId*

*Test Purpose: <<_requirement-49>>*

*Test method:*

For each Dataset, Stitched Mosaic, and Dataset Series offered by the serv-er under test, sends a valid DescribeEOCoverageSet request to server un-der test. Check that the identifier of a Dataset, a Stitched Mosaic, or a Da-taset Series is equal to the eoId parameter value in the request. Test passes if all individual tests pass.

==== DescribeEOCoverageSet Request Containment

*Test id: /conf/eowcs/describeEOCoverageSet-request-containment*

*Test Purpose: <<_requirement-50>>*

*Test method:*

Send otherwise DescribeEOCoverageSet requests contain a containment parameter and this parameter has one of the values:
* “contains”
* “overlaps”
* invalid values
Pass test if appropriate valid results or exceptions, resp., are delivered.

==== DescribeEOCoverageSet Request Dimension

*Test id: /conf/eowcs/describeEOCoverageSet-request-dimension*

*Test Purpose: <<_requirement-51>>*

*Test method:*

Send otherwise valid DescribeEOCoverageSet requests to server under test which contain duplicate, and send requests which contain no duplicate dimension parameters. Do so for requests with single,and multiple di-mensionTrim. Verify that, whenever at least one duplicate dimension occurs, an exception is returned and a normal response otherwise.

==== DescribeEOCoverageSet Request CRS

*Test id: /conf/eowcs/describeEOCoverageSet-request-crs*

*Test Purpose: <<_requirement-52>>*

*Test method:*

Send otherwise valid DescribeEOCoverageSet requests to server under test which contain:
* WGS84 [4] as spatial and ISO 8601 [2] as temporal CRS for the coor-dinates in trim request
*  Other CRS for the coordinates in trim requests
Pass test if appropriate valid results or exceptions, resp., are delivered.

==== DescribeEOCoverageSet Response Structure

*Test id: /conf/eowcs/describeEOCoverageSet-response-structure*

*Test Purpose: <<_requirement-53>>*

The response to a successful DescribeEOCoverageSet request shall con-sist of a EOWCS::EOCoverageSetDescription structure as defined in Table 11, Figure 9 and the XML Schema being part of this standard.
Dependency: [OGC 09-110r4] Subclause 8.3.2 (http://www.opengis.net/doc/IS/WCS/2.0/clause/8)
Test method:    Send a DescribeEOCoverageSet request to server under test, check the result consist of a EOWCS::EOCoverageSetDescription structure.

==== DescribeEOCoverageSet Response EO Metadata

*Test id: /conf/eowcs/describeEOCoverageSet-response-eo-metadata*

*Test Purpose: <<_requirement-54>>*

*Test method:*

Send a valid DescribeEOCoverageSet requests to server under test, check that each WCS::CoverageDescription listed in the response contains one EOWCS::EOMetadata element and this element contains the EO Metadata component of the EO Coverage to be described.

==== DescribeEOCoverageSet Response EO Section CoverageDescriptions

*Test id: /conf/eowcs/describeEOCoverageSet-response-section-coverageDescriptions*

*Test Purpose: <<_requirement-55>>*

*Test method:*

Send otherwise valid DescribeEOCoverageSet requets contain a sec-tions element and this element contains one of the section parameter values:
* “CoverageDescription”
*  “All”
* invalid values
Pass test if appropriate valid results or exceptions, resp., are delivered.

==== DescribeEOCoverageSet Response EO Section DatasetSeriesDescriptions

*Test id: /conf/eowcs/describeEOCoverageSet-response-section-datasetSeriesDescriptions*

*Test Purpose: <<_requirement-56>>*

*Test method:*

Send otherwise valid DescribeEOCoverageSet requets contain a sec-tions element and this element contains one of the section parameter values:
* “DatasetSeriesDescriptions”
*  “All”
* invalid values
Pass test if appropriate valid results or exceptions, resp., are delivered.

==== DescribeEOCoverageSet Response eoId

*Test id: /conf/eowcs/describeEOCoverageSet-response-eoId*

*Test Purpose: <<_requirement-57>>*

*Test method:*

Send a valid DescribeEOCoverageSet request containing a wcs:Cover-ageDescription section to server under test. Check that each EO Coverage referred to by one of the objects identified in the eoId request parameter appears at most once.

==== DescribeEOCoverageSet Response Reffered

*Test id: /conf/eowcs/describeEOCoverageSet-response-referred*

*Test Purpose: <<_requirement-58>>*

*Test method:*

For each Send a valid DescribeEOCoverageSet requests to server under test, check that each WCS::CoverageDescription listed in the re-sponse is at least contained in one of the  EOWCS::EOMetadata element and that this element contains the EO Metadata component of the EO Coverage to be described.
For each EOWCS::DatasetSeries offered by the server under test:
* Send a valid DescribeEOCoverageSet request. Check that each WCS::CoverageDescription listed in the response is at least re-ferred to by one EOWCS::DatasetSeries also contained in the re-sponse.
Test passes if all individual tests pass.

==== DescribeEOCoverageSet Response Containment

*Test id: /conf/eowcs/describeEOCoverageSet-response-containment*

*Test Purpose: <<_requirement-59>>*

The response to a successful DescribeEOCoverageSet request containing a wcs:CoverageDescription section shall contain only descriptions of those EO Coverages whose spatial footprint defined by its eop:EarthObservation/om:featureOfInterest/eop:Foot-print
- overlaps with the spatial request extent, and the request parameter con-tainment is of value overlaps or is omitted,
- is completely contained within the spatial request extent, and the request parameter containment is of value contains
whereby all spatial coordinates are expressed in WGS84 [2].
Test method:    Send otherwise valid DescribeEOCoverageSet requests containing a wcs:CoverageDescription section and a spatial trim to server under test. Check that:
* if the request parameter containment is of value overlaps or is omit-ted,  the response contains only descriptions of those EO Coverages whose spatial footprint defined by its eop:EarthObservat-ion/om:featureOfInterest/eop:Footprint overlaps with the spatial request extent;
* if the request parameter containment is of value contains,  the re-sponse contains only descriptions of those EO Coverages whose spa-tial footprint defined by its eop:EarthObservation/om:featureOfInterest/eop:Footprint is completely contained within the spatial request extent.
Pass test if both checks succeed.

==== DescribeEOCoverageSet Response PhenomenonTime

*Test id: /conf/eowcs/describeEOCoverageSet-response-phenomenonTime*

*Test Purpose: <<_requirement-60>>*

The response to a successful DescribeEOCoverageSet request containing a wcs:CoverageDescription section shall contain only descriptions of EO Coverages whose time interval defined by its eop:Earth-Observation/om:phenomenon-Time/gml:TimePeriod/gml:beginPosition and eop:Earth-Observation/om:phenomenon-Time/gml:TimePeriod/gml:endPosition elements in eowcs:EOMetadata
- overlaps with the request time extent,and the request parameter con-tainment is of value overlaps or is omitted,
- is completely contained within the request time extent, and the request parameter containment is of value contains,
whereby all temporal coordinates are expressed in ISO 8601 [2].
Test method:    Send otherwise valid DescribeEOCoverageSet requests containing a wcs:CoverageDescription section and a time interval to server un-der test. Check that:
* if the request parameter containment is of value overlaps or is omit-ted,  the response contains only descriptions of EO Coverages whose time interval defined by its eop:EarthObservation/om:phen-omenonTime/gml:TimePeriod/gml:beginPosition and eop:EarthObservation/om:phenomenonTime/gml:Time-Period/gml:endPosition elements in eowcs:EOMetadata overlaps with the request time extent;
* if request parameter containment is of value contains,  the response contains only descriptions of EO Coverages whose time interval de-fined by its eop:EarthObservation/om:phenomenonTime/ gml:TimePeriod/gml:beginPosition and eop: Earth-Observation/om:phenomenonTime/gml:TimePeriod/ gml:endPosition elements in eowcs:EOMetadata is complete-ly contained within the request time extent;
Pass test if both checks succeed.

==== DescribeEOCoverageSet Response Trim Omitted

*Test id: /conf/eowcs/describeEOCoverageSet-response-trim-omitted*

*Test Purpose: <<_requirement-61>>*

*Test method:*

Send otherwise valid DescribeEOCoverageSet with a trimming in actual boundary of the object and without a trimming to server under test. Check that both responses are not exceptions and equal.

==== DescribeEOCoverageSet Response Bound Omitted

*Test id: /conf/eowcs/describeEOCoverageSet-response-bound-omitted*

*Test Purpose: <<_requirement-62>>*

*Test method:*

Send otherwise valid DescribeEOCoverageSet requests with a lower or upper bound omitted to server under test. Check that the responses are the same when they are indicated in actual lower or upper bound of the ob-jects.

==== DescribeEOCoverageSet Response CoverageSubtype

*Test id: /conf/eowcs/describeEOCoverageSet-response-coverageSubtype*

*Test Purpose: <<_requirement-63>>*

*Test method:*

Send a valid DescribeEOCoverageSet request to server under test. Check that each Coverage listed contains the corresponding value in its WCS::CoverageSubtype element.

==== DescribeEOCoverageSet Response Count

*Test id: /conf/eowcs/describeEOCoverageSet-response-count*

*Test Purpose: <<_requirement-64>>*

*Test method:*

Send a valid DescribeEOCoverageSet request containing a count param-eter with a value lower than the value of the CountDefault element to server under test. Check that the sum of the numbers of CoverageDe-scription and DatasetSeriesDescription elements is less or equal to the value of the count parameter.

==== DescribeEOCoverageSet Response numberMatched

*Test id: /conf/eowcs/describeEOCoverageSet-response-numberMatched*

*Test Purpose: <<_requirement-65>>*

*Test method:*

Send a valid DescribeEOCoverageSet request containing a count param-eter with a value lower than the value of the CountDefault element to server under test. Check that the sum of the numbers of CoverageDe-scription and DatasetSeriesDescription elements is higher or equal to the value of the reported numberMatched parameter.

==== DescribeEOCoverageSet Response numberReturned

*Test id: /conf/eowcs/describeEOCoverageSet-response-numberReturned*

*Test Purpose: <<_requirement-66>>*

*Test method:*

Send a valid DescribeEOCoverageSet request containing a count param-eter with a value lower than the value of the CountDefault element to server under test. Check that the sum of the numbers of CoverageDe-scription and DatasetSeriesDescription elements is equal to the value of the reported numberReturned parameter.

==== Band Subsetting

*Test id: /conf/eowcs/band-subsetting*

*Test Purpose: <<_requirement-67>>*

Implementations of this EO-WCS shall support the WCS 2.0 Range Sub-setting Extension [OGC 12-040].
Dependency: http://www.opengis.net/spec/WCS_service-extension_range-subsetting/1.0/conf/record-subsetting
Test method:    Determine the list of supported extensions via a valid GetCapabilities re-quest; check that the extension required is listed.

==== Scaling

*Test id: /conf/eowcs/scaling+interpolation*

*Test Purpose: <<_requirement-68>>*

Implementations of this EO-WCS shall support the WCS 2.0 Scaling Ex-tension [OGC 12-039].
Dependency: http://www.opengis.net/spec/WCS_service-extension_scaling/1.0/conf/scaling
Test method:    Determine the list of supported extensions via a valid GetCapabilities re-quest; check that the extension required is listed.

==== Interpolation

*Test id: /conf/eowcs/interpolation*

*Test Purpose: <<_requirement-69>>*

Implementations of this EO-WCS shall support the WCS 2.0 Interpolation Extension [OGC 12-049].
Dependency: http://www.opengis.net/spec/WCS_service-extension_interpolation/1.0/conf/interpolation
Test method:    Determine the list of supported extensions via a valid GetCapabilities re-quest; check that the extension required is listed.

==== CRS-predefined

*Test id: /conf/eowcs/crs-predefined*

*Test Purpose: <<_requirement-70>>*

Implementations of this EO-WCS shall support the WCS 2.0 CRS Exten-sion [OGC 11-053].
Dependency: http://www.opengis.net/spec/WCS_service-extension_crs/1.0/conf/crs
Test method:    Determine the list of supported extensions via a valid GetCapabilities re-quest; check that the extension required is listed.

==== Encodings

*Test id: /conf/eowcs/encodings*

*Test Purpose: <<_requirement-71>>*

Implementations of this EO-WCS shall support at least one of the WCS 2.0 coverage format encodings GeoTIFF [OGC12-100r1], NetCDF [OGC 11-010], and JPEG2000 [OGC 11-011].
Dependency: http://www.opengis.net/spec/GMLCOV_geotiff-coverages/1.0/conf/geotiff-coverage, http://www.opengis.net/spec/WCS_encoding_netcdf/1.0/conf/netcdf, http://www.opengis.net/spec/WCS_encoding_jpeg2000/1.0/conf/jpeg2000
Test method:    Determine the list of supported extensions via a valid GetCapabilities re-quest; check that the extension required is listed.

==== Protocol-bindings

*Test id: /conf/eowcs/protocol-bindings*

*Test Purpose: <<_requirement-72>>*

*Test method:*

Determine the list of supported extensions via a valid GetCapabilities re-quest; check that the extension required is listed.

=== Conformance Test Class: eowcs_get-kvp

==== Eowcs_get-kvp/Mandatory

*Test id: /conf/eowcs/eowcs_get-kvp/mandatory*

*Test Purpose: <<_requirement-73>>*

Implementations of this EO-WCS which support the eowcs_get-kvp re-quirements class shall support the WCS 2.0 protocol extension GET/KVP [OGC 09-147r3].
Dependency: http://www.opengis.net/spec/WCS_protocol-binding_get-kvp/1.0/conf/get-kvp
Test method:    Determine the list of supported extensions via a valid GetCapabilities re-quest; check that the extension required is listed.

==== Eowcs_get-kvp/Conformance Class in Profile

*Test id: /conf/eowcs/eowcs_get-kvp/conformance-class-in-profile*

*Test Purpose: <<_requirement-74>>*

Implementations of this EO-WCS which support the eowcs_get-kvp re-quirements class shall include the following URI in a Profile element in the ServiceIdentification in a GetCapabilities response:
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.0/conf/eowcs_get-kvp
Test method:    Determine the list of supported extensions via a valid GetCapabilities re-quest; check that the extension required is listed.

==== Eowcs_get-kvp/describeEOCoverageSet Request

*Test id: /conf/eowcs/eowcs_get-kvp/describeEOCoverageSet-request*

*Test Purpose: <<_requirement-75>>*

The request parameter in the DescribeEOCoverageSet request parameter of a DescribeEOCoverageSet request shall be indicated as fol-lows:
    request=DescribeEOCoverageSet
Test method:    Send a valid get-kvp DescribeEOCoverageSet request as defined. Check that the response is not an exception.

==== Eowcs_get-kvp/describeEOCoverageSet eoid

*Test id: /conf/eowcs/eowcs_get-kvp/describeEOCoverageSet-eoid*

*Test Purpose: <<_requirement-76>>*

The eoId parameter in the DescribeEOCoverageSet request parame-ter of a DescribeEOCoverageSet request shall be indicated as follows, for parameter values v1, …, vn:
    eoid= v1,…,vn
Test method:    Send a valid get-kvp DescribeEOCoverageSet request as defined. Check that the response is not an exception.

==== Eowcs_get-kvp/describeEOCoverageSet Containment

*Test id: /conf/eowcs/eowcs_get-kvp/describeEOCoverageSet-containment*

*Test Purpose: <<_requirement-77>>*

The containment parameter in the DescribeEOCoverageSet re-quest parameter of a DescribeEOCoverageSet request shall be indicated as follows:
    containment=overlaps
or  containment=contains
Test method:    Send a valid get-kvp DescribeEOCoverageSet request as defined. Check that the response is not an exception.

==== Eowcs_get-kvp/describeEOCoverageSet Subset

*Test id: /conf/eowcs/eowcs_get-kvp/describeEOCoverageSet-subset*

*Test Purpose: <<_requirement-78>>*

The trim parameters in the DescribeEOCoverageSet request parame-ter of a DescribeEOCoverageSet request shall be indicated through a pos-sibly empty set of subset specifications, each one with key “subset” and value specification given by a SubsetSpec adhering to this EBNF syn-tax [3] and the resp. XML definitions [6]:
    SubsetSpec:     dimension ( interval )
    dimension:      long | lat | phenomenonTime
    interval:       low , high
    low:                point   | *
    high:           point   | *
    point:          number  | " token "     // " = ASCII 0x42
Test method:    Send a valid get-kvp DescribeEOCoverageSet request as defined. Check that the response is not an exception.

=== Conformance Test Class: eowcs_soap

==== Eowcs_soap/Mandatory

*Test id: /conf/eowcs/eowcs_soap/mandatory*

*Test Purpose: <<_requirement-79>>*

Implementations of this EO-WCS which support the eowcs_soap require-ments class shall support the WCS 2.0 protocol extension SOAP [OGC 09-149r1].
Dependency: http://www.opengis.net/spec/WCS_protocol-binding_soap/1.0/conf/soap
Test method:    Determine the list of supported extensions via a valid GetCapabilities re-quest; check that the extension required is listed.

==== Eowcs_soap/Conformance Class in Profile

*Test id: /conf/eowcs/eowcs_soap/conformance-class-in-profile*

*Test Purpose: <<_requirement-80>>*

Implementations of this EO-WCS which support the eowcs_soap require-ments class shall include the following URI in a Profile element in the ServiceIdentification in a GetCapabilities response:
http://www.opengis.net/spec/WCS_application-profile_earth-observation/1.0/conf/eowcs_soap
Test method:    Determine the list of supported extensions via a valid GetCapabilities re-quest; check that the extension required is listed.

==== Eowcs_soap/describeEOCoverageSet Request Structure

*Test id: /conf/eowcs/eowcs_soap/describeEOCoverageSet-request-structure*

*Test Purpose: <<_requirement-81>>*

*Test method:*

Send otherwise soap DescribeEOCoverageSet requests contain:
* exactly one Body element containing exactly one DescribeEOCover-ageSet element;
* exactly one Body element containing more than one DescribeEOCov-erageSet element;
* exactly one Body element containing no DescribeEOCoverageSet ele-ment;
* more than one Body element;
* without a Body elment;
Pass test if appropriate valid results or exceptions, resp., are delivered.

==== Eowcs_soap/describeEOCoverageSet Request Structure

*Test id: /conf/eowcs/eowcs_soap/describeEOCoverageSet-request-structure*

*Test Purpose: <<_requirement-82>>*

*Test method:*

Send a valid soap DescribeEOCoverageSet request to sever under test. Check response whether the condition is fulfilled.

==== Eowcs_soap/wsdl

*Test id: /conf/eowcs/eowcs_soap/wsdl*

*Test Purpose: <<_requirement-83>>*

*Test method:*

For the service under test, retrieve the WSDL description and issue re-quests which make use of this service definition. Check that the service can be addressed and that queries can be retrieved properly.

-- end of ATS –
